In [7]:
import pymongo 
from pymongo import MongoClient
import pandas as pd
import json

client = MongoClient("mongodb://Lori:Les4783!@ds223756.mlab.com:23756/heroku_r58qkhd7")

db = client["heroku_r58qkhd7"]
collection = db["model"]

In [8]:
    
from flask import Flask, render_template, redirect, jsonify, request
from flask_pymongo import PyMongo
import pandas as pd
import pymongo
from pymongo import MongoClient
import os
from bson.objectid import ObjectId
import pprint
import sys
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import geopy
from geopy import distance
from geopy.distance import vincenty
# from tqdm import tqdm
# tqdm.pandas()
import tensorflow as tf
from keras.utils import to_categorical
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from collections import Counter
from scipy import stats
from dateutil import parser
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)
import numpy as np
from keras.models import load_model

In [9]:
# df = pd.read_json("museums.json")
# df.head()

df = pd.read_csv("test_data.csv")
df.head()


Unnamed: 0  MinNights  Hood  SqFt  #Reviews  #Guests  Listing Count  \
0           0          1    43    20        95        3              1   
1           1          0    33    15       287        1              1   
2           2          3    37    20       214        1              2   
3           3          2    54    20       132        1              2   
4           4          4     6    20       178        1              2   

   Security  CleanFee  Dist  BA  BR  Beds  Acc  Price  #Booked  \
0         0        69  5069   4   3     4    4      3       98   
1         0        40  4988   1   1     1    3      1      398   
2        18        55  1422   1   1     1    2      2      209   
3         0        48  3255   4   1     1    2      1      131   
4        15        34  4128   1   1     1    2      0      175   

                                           Name  Polarity  
0                 Spacious Cottage in Mid-City!      4601  
1                Fully Furnished Cozy Apartment      4272  
2              Maison Mandeville in the Marigny      5192  
3  MARDI GRAS YA’LL HUNDREDS 5 STAR REVIEWS !!!      5279  
4      Historical Bywater Mother in Law Cottage      5326

In [ ]:
df.to_csv('hoods.csv')

In [ ]:

df["Name"] = df["Name"].str.replace(".","")

df1 = df.set_index('Name')


In [10]:
df.to_json("test_data.json", orient="records")
# collection.insert(file_data)

In [ ]:
df.to_json("test_data.json")

In [11]:
with open("test_data.json") as f:
    file_data = json.load(f)
    collection.insert(file_data)

c:\users\user\miniconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [2]:
with open("test_data.csv") as f:
    file_data = json.load(f)
#     print(file_data)
df = pd.read_json('hoods.json')
df.keys()


UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13443: character maps to <undefined>

In [ ]:

df = pd.read_json('test_data.json')
df.head()

In [34]:


listings = []
prediction=[]
# test1 = pd.DataFrame(prediction)

myquery = {"Name":{ '$regex': ('Uptown Cottage') }}

# myquery = {"price":{ "$eq": "300" }}
print('query', collection.find(myquery))
for json in collection.find(myquery):
    data = {}
    data.update({
    'MinNights': json['MinNights'],
    'Hood' : json['Hood'],
    'SqFt' : json['SqFt'],
    '#Reviews': json['#Reviews'],
    '#Guests' :json['#Guests'],
    'Listing Count' : json['Listing Count'],
    'Security':json['Security']      ,
    'CleanFee':json['CleanFee'],
    'Dist':json['Dist'],
    'BA':json['BA'],
    'BR':json['BR'],
    'Beds':json['Beds'],
    'Acc': json['Acc'],
    '#Booked':json['#Booked'],
    'Price':json['Price'],
    'Name':json['Name'],
                'Polarity':json['Polarity']

    })
    listings.append(data)
listings



query <pymongo.cursor.Cursor object at 0x0000000025DD86A0>


[{'MinNights': 1,
  'Hood': 19,
  'SqFt': 20,
  '#Reviews': 180,
  '#Guests': 3,
  'Listing Count': 1,
  'Security': 14,
  'CleanFee': 26,
  'Dist': 4938,
  'BA': 1,
  'BR': 1,
  'Beds': 1,
  'Acc': 2,
  '#Booked': 295,
  'Price': 1,
  'Name': 'Uptown Cottage (Best reviews in New Orleans!)',
  'Polarity': 4649},
 {'MinNights': 10,
  'Hood': 33,
  'SqFt': 20,
  '#Reviews': 19,
  '#Guests': 1,
  'Listing Count': 6,
  'Security': 26,
  'CleanFee': 48,
  'Dist': 5722,
  'BA': 1,
  'BR': 1,
  'Beds': 1,
  'Acc': 2,
  '#Booked': 37,
  'Price': 1,
  'Name': 'Uptown Cottage  Great location Pet Friendly',
  'Polarity': 897},
 {'MinNights': 1,
  'Hood': 8,
  'SqFt': 20,
  '#Reviews': 204,
  '#Guests': 3,
  'Listing Count': 1,
  'Security': 0,
  'CleanFee': 0,
  'Dist': 2876,
  'BA': 1,
  'BR': 2,
  'Beds': 2,
  'Acc': 4,
  '#Booked': 389,
  'Price': 1,
  'Name': 'Adorable 2br Uptown Cottage',
  'Polarity': 4267},
 {'MinNights': 2,
  'Hood': 62,
  'SqFt': 20,
  '#Reviews': 106,
  '#Guests': 0,
  

In [33]:
myquery1={}
listings1=[]
for json1 in collection.find(myquery):
    data1 = {}
    data1.update({
    'MinNights': json['MinNights'],
    'Hood' : json['Hood'],
    'SqFt' : json['SqFt'],
    '#Reviews': json['#Reviews'],
    '#Guests' :json['#Guests'],
    'Listing Count' : json['Listing Count'],
    'Security':json['Security']      ,
    'CleanFee':json['CleanFee'],
    'Dist':json['Dist'],
    'BA':json['BA'],
    'BR':json['BR'],
    'Beds':json['Beds'],
    'Acc': json['Acc'],
    '#Booked':json['#Booked'],
    'Price':json['Price'],
    'Name':json['Name'],
                'Polarity':json['Polarity']

    })
#     listings.append(data)
    listings1.append(data1)


In [29]:
test = pd.DataFrame(listings)
test1 = pd.DataFrame(listings1)
x1 = test.drop('Price', axis=1)
x = x1.drop('Name', axis=1)
y = test['Price']


In [30]:

x2=test1.drop('Name', axis=1)
x1 = x2.drop('Price', axis=1)
y1 = test1['Price']
# model=load_model("airbnb.h5")


In [31]:
test = pd.DataFrame(listings)
test1 = pd.DataFrame(listings1)
x1 = test.drop('Price', axis=1)
x = x1.drop('Name', axis=1)
y = test['Price']

x2=test1.drop('Name', axis=1)
x1 = x2.drop('Price', axis=1)
y1 = test1['Price']
model=load_model("airbnb.h5")

# clf = RandomForestClassifier(n_estimators=11)
# scoring = 'accuracy'
# score = cross_val_score(clf, x1, y1, cv=k_fold, n_jobs=1, scoring=scoring)
# clf.fit(x1,y1)
# pred=()
# prediction1=clf.predict(x)
prediction1=model.predict(x)
print(prediction1)
if prediction1[0] < y[0]:
    pred='Great Deal!'
if prediction1[0]==y[0]:
    pred='Right on the money!'
if prediction1[0] >y[0]:
    pred='Bad Deal'
prediction2=pd.DataFrame({"pred":pred, 'modl':prediction1[0],"sample":y})
prediction=prediction2.to_json(orient="records")
prediction2

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
print(x)

    #Booked  #Guests  #Reviews  Acc  BA  BR  Beds  CleanFee  Dist  Hood  \
0       295        3       180    2   1   1     1        26  4938    19   
1        37        1        19    2   1   1     1        48  5722    33   
2       389        3       204    4   1   2     2         0  2876     8   
3       209        0       106    4   3   1     1        40  5028    62   
4        15        0         6    4   4   2     2        78  4972     1   
5        88        0        17    4   4   2     2        69  5764    67   
6       237        1       102    2   1   1     1        50  5203    14   
7       170        0        64    2   1   0     1        55  4413    41   
8       110        0        38    4   4   2     4        69  5547    67   
9       129        5        36    6   4   3     5        64  4861    38   
10       84        3        24    4   4   2     2        88  5660    67   
11      254        0        69    4   1   1     4        48  5700    67   
12      170        3     